config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  resources :users
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"

  resources :professionals do
    resources :appointments
    get "export_one", to: "export#export_professional"
  end
  get "export_all", to: "export#export_all"
end

app/models/polycon/models/professional.rb
module Polycon
    module Models
        class Professional
            attr_accessor :name
            def initialize(name)
                @name=name
            end

            def create_folder()
                Dir.mkdir(Helpers.path<<"/#{@name}")
            end

            def self.exist?(name) #verify if a folder w/ that name exists
                Dir.exist?(Helpers.path<<"/#{name}")
            end

            def self.rename_professional(old_name, new_name)
                File.rename(Helpers.path << "/#{old_name}" , Helpers.path << "/#{new_name}")
            end

            def self.list_professionals()
                if Dir.children(Helpers.path).empty?
                    puts "No hay profesionales cargados en el sistema actualmente"
                else
                    puts "Los profesionales registrados en el sistema son los siguientes:"
                    puts Dir.children(Helpers.path)
                end
            end

            def self.delete_professional(name)
                begin
                    Dir.delete(Helpers.path << "/#{name}") #"Dir.delete" produce an error if the file is not empty
                rescue SystemCallError
                    warn "ERROR: El directorio \"#{name}\", no se encuentra vacio, por lo que la eliminacion se vio interrumpida"
                else
                    puts "El directorio \"#{name}\" fue eliminado con exito"
                end
            end

            # def has_appointments?()
            #     self.appointments.empty?
            # end
        end
    end
end

app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments, dependent: :restrict_with_error
    
    validates :name, :surname, presence: { message: " is required"}, length: {in: 3..45, too_long: "Must be %{count} charcters max"}
    validate :full_name

    def full_name
        if name.present? and surname.present?
            aux = Professional.where("name= ? and surname= ?", name, surname).first
            if aux
                errors.add("#{:name} and #{:surname}", " : The professional already exist") unless id == aux.id
            end
        end
    end

    def to_s
        "#{name} #{surname}"
    end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: [:show, :edit, :update, :destroy]

  # GET /professionals
  def index
    redirect_if_not_logged
    @professionals = Professional.all
  end

  # GET /professionals/1
  def show
    redirect_if_not_logged
  end

  # GET /professionals/new
  def new
    redirect_if_not_logged
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
    redirect_if_not_logged
  end

  # POST /professionals
  def create
    redirect_if_not_logged
    @professional = Professional.new(professional_params)

    if @professional.save
      redirect_to @professional, notice: 'Professional was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /professionals/1
  def update
    redirect_if_not_logged
    if @professional.update(professional_params)
      redirect_to @professional, notice: 'Professional was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /professionals/1
  def destroy
    redirect_if_not_logged
    if @professional.destroy
      notice = "The professional #{@professional.name} #{@professional.surname} was deleted successfully"
    else
      notice = "ERROR; The professional #{@professional.name} #{@professional.surname} has appointments"
    end
    redirect_to professionals_url, notice: notice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:name, :surname)
    end
    
    def redirect_if_not_logged
      if session[:user_id].nil?
          redirect_to login_path
      end
    end

    def redirect_if_not_admin
      if current_user.rol.name != "administracion"
        redirect_to root_path
      end
    end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<%= render "layouts/navbar.html.erb"%>
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professionals/edit.html.erb
<%= render "layouts/navbar.html.erb"%>
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

app/views/professionals/index.html.erb
<%= render "layouts/navbar.html.erb"%>
<div>
  <p id="notice"><%= notice %></p>

  <h1>Professionals</h1>
  <% if isAdminUser? %>
    <%= link_to 'New Professional', new_professional_path %>
    <%= link_to 'Export Schedule', export_all_path %>
  <% end %>

  <div>
    <table>
      <thead>
        <tr>
          <th>| Name |</th>
          <th>| Surname |</th>
          <th></th>
          <th>Options</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @professionals.each do |professional| %>
          <tr>
            <td><%= professional.name %></td>
            <td><%= professional.surname %></td>
            <td>
            <td><%= link_to 'Show', professional %>
              <%= link_to 'Appointments', professional_appointments_path(professional) %>
              <% if isAdminUser? %>
              <%= link_to 'Edit', edit_professional_path(professional) %>
              <%= link_to 'Destroy', professional, method: :delete, data: { confirm: "Are you sure you want to delete the professional #{professional.name} #{professional.surname}?" } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <div><br>

  <%= link_to 'Back', root_path %>
</div>

app/views/professionals/new.html.erb
<%= render "layouts/navbar.html.erb"%>
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

app/views/professionals/show.html.erb
<%= render "layouts/navbar.html.erb"%>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @professional.surname %>
</p>

<% if isAdminUser? %>
<%= link_to 'Edit', edit_professional_path(@professional) %> |
<% end %>
<%= link_to 'Back', professionals_path %>