config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  resources :users
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"

  resources :professionals do
    resources :appointments
    get "export_one", to: "export#export_professional"
  end
  get "export_all", to: "export#export_all"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional
  validates :date, :name, :surname, :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validate :hour_availability, :appointment_hour

  #round the minutes to 0 or 30
  def self.round_to_30_minutes(t)
    
  end

  #validate if the appointment's hour is between 8..20
  def appointment_hour
    if date.present?
      errors.add(:date, "hour must be bewween 8 and 20") unless ((8..20).include? date.hour)
      errors.add(:date, "minutes of the appointment must be 0 or 30") unless [0,30].include? date.min
    end
  end

  # validate if professional+date do ot exist in the database
  def hour_availability
    if date.present?

      # rounded = Time.at((date.to_time.to_i / 1800.0).round * 1800)
      # date= date.is_a?(DateTime) ? rounded.to_datetime : rounded

      aux = Appointment.where("date= ? and professional_id= ?", date, professional_id).first
      if aux
        errors.add(:date, " : The professional already has an appointment on that date and hour") unless id == aux.id
      end
    end
  end

  def schedule_format()
    "Prof. #{professional} - #{surname} #{name}"
  end
end

app/models/polycon/models/appointment.rb
module Polycon
    module Models
        class Appointment
            attr_accessor :date, :prof, :info
            def initialize(date, prof, name, surname, phone, notes=nil)
                @date=date
                @prof=prof
                @info={surname: surname, name: name, phone: phone}
                if notes
                    @info["notes"]= notes
                else
                    @info["notes"]= ""
                end
            end

            def create_file()
                File.open(Helpers.path << "/#{@prof}/#{date}.paf",'w') do |appointment|
                    info.each {|(key,value)| appointment.puts "#{key}: #{value}"}
                end
            end

            def self.exist?(prof, date) #verify if a file w/ that name exists
                File.exist?(Helpers.path<<"/#{prof}/#{date}.paf")
            end

            def self.show_file(prof, date)
                File.readlines(Helpers.path << "/#{prof}/#{date}.paf").each do |line| puts line end 
            end

            def self.cancel_appointment(prof, date)
                begin
                File.delete(Helpers.path << "/#{prof}/#{date}.paf")
                rescue
                    warn "ERROR: No se ha podido cancelar la cita del profesional #{prof} para el dia #{date}"
                else
                    warn "Se ha eliminado la cita del profesional #{prof} para el dia #{date}"
                end
            end

            def self.cancel_all_files(prof)
                if Dir.children(Helpers.path << "/#{prof}").empty?
                    puts "No hay citas cargadas para el profesional \"#{prof}\" actualmente"
                else
                    begin
                        Dir.children(Helpers.path << "/#{prof}").each {|file| File.delete(Helpers.path << "/#{prof}/#{file}")}
                    rescue
                        warn "ERROR: No se ha podido cancelar todas las citas del profesional #{prof}"
                    else
                        warn "Se ha eliminado todas las citas del profesional #{prof}"
                    end
                end
            end

            def self.rename_file(prof, old_date, new_date)
                begin
                File.rename(Helpers.path << "/#{prof}/#{old_date}.paf",Helpers.path << "/#{prof}/#{new_date}.paf")
                rescue
                    warn "ERROR: No se ha podido reasignar la cita del profesional #{prof} para el dia #{new_date}, por favor, intente nuevamente"
                else
                    warn "Se ha modificado correctamente la cita del profesional #{prof} del dia #{old_date} para el dia #{new_date}"
                end
            end

            def self.list_appointments(prof, date=nil)
                #remuevo la extension ".paf" de los archivos para que solo muestre las fechas
                aux=Dir.children(Helpers.path << "/#{prof}").each {|file| file.slice! ".paf"}
                if aux.empty? #tiene citas?
                    puts "No hay citas cargadas para el profesional \"#{prof}\" actualmente"
                else
                    if not date
                        puts "El profesional \"#{prof}\" posee las siguientes citas:"
                        puts aux
                    else
                        puts "El profesional \"#{prof}\" posee las siguientes citas el dia #{date}:"
                        aux.each do |file|
                            puts file if file[0...10]==date
                        end
                    end
                end
            end

            def self.edit_file(prof, date, options=nil)
                begin
                    aux={}
                    File.readlines(Helpers.path << "/#{prof}/#{date}.paf").each do |line|
                        aux[line.split(':')[0]]=line.split(':')[1]
                    end
                    options.each do |(key,value)|
                        aux[key.to_s]=value
                    end
                    File.open(Helpers.path << "/#{prof}/#{date}.paf",'w') do |appointment|
                        aux.each {|(key,value)| appointment.puts "#{key}: #{value}"}
                    end
                rescue
                    warn "ERROR: No se ha podido modificar la informacion de la cita del profesional #{prof} para el dia #{date}, por favor, intente nuevamente"
                else
                    warn "Se ha modificado correctamente la informacion de la cita del profesional #{prof} del dia #{date}"
                end
            end
        end
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_professional
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /professional/1/appointments
  def index
    redirect_if_not_logged
    @appointments = @professional.appointments
  end

  # GET /professional/1/appointments/1
  def show
    redirect_if_not_logged
  end

  # GET /professional/1/appointments/new
  def new
    redirect_if_not_logged
    redirect_if_consul
    @appointment = @professional.appointments.new()
  end

  # GET /professional/1/appointments/1/edit
  def edit
    redirect_if_not_logged
    redirect_if_consul
  end

  # POST /professional/1/appointments
  def create
    redirect_if_not_logged
    redirect_if_consul
    @appointment = @professional.appointments.new(appointment_params)
    if @appointment.save
      redirect_to [@professional,@appointment], notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /professional/1/appointments/1
  def update
    redirect_if_not_logged
    redirect_if_consul
    if @appointment.update(appointment_params)
      redirect_to [@professional,@appointment], notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /professional/1/appointments/1
  def destroy
    redirect_if_not_logged
    redirect_if_consul
    @appointment.destroy
    redirect_to professional_appointments_url(@professional), notice: 'Appointment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:professional_id])
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :name, :surname, :phone, :note)
    end
    

    def redirect_if_not_logged
      if session[:user_id].nil?
          redirect_to login_path
      end
    end

    def redirect_if_consul
      if current_user.rol.name == "consulta"
        redirect_to root_path
      end
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
    def full_name(name, surname)
        "Paciente #{name} #{surname}"
    end

    def formadate(date)
        I18n.l(date, format: :long)
    end
end

app/views/appointments/_form.html.erb
<%= render "layouts/navbar.html.erb"%>
<%= form_with(model: [professional, appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<%= render "layouts/navbar.html.erb"%>
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<%= link_to 'Show', [@professional, @appointment] %> |
<%= link_to 'Back', professional_appointments_path %>

app/views/appointments/index.html.erb
<%= render "layouts/navbar.html.erb"%>
<p id="notice"><%= notice %></p>

<div>
  <h1>Appointments</h1>
  <% if not isConsuUser? %>
    <%= link_to 'New Appointment', new_professional_appointment_path %>
    <%= link_to 'Export Schedule', professional_export_one_path %>
  <% end %>
  <br>

  <table>
    <thead>
      <tr>
        <th>| Date |</th>
        <th></th>
        <th>| Full Name |</th>
        <th>| Phone |</th>
        <th>| Note |</th>
        <th>Options</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @appointments.each do |appointment| %>
        <tr>
          <td><%= formadate(appointment.date) %></td>
          <td></td>
          <td><%= full_name(appointment.name, appointment.surname) %></td>
          <td><%= appointment.phone %></td>
          <td><%= appointment.note %></td>

          <td>
          <%= link_to 'Show', [@professional,appointment] %>
          <% if not isConsuUser? %>
          <%= link_to 'Edit', edit_professional_appointment_path(@professional,appointment) %>
          <%= link_to 'Destroy', [@professional,appointment], method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Back', professionals_path %>
</div>

app/views/appointments/new.html.erb
<%= render "layouts/navbar.html.erb"%>
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<%= link_to 'Back', professional_appointments_path %>

app/views/appointments/show.html.erb
<%= render "layouts/navbar.html.erb"%>
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Note:</strong>
  <%= @appointment.note %>
</p>

<% if not isConsuUser? %>
<%= link_to 'Edit', edit_professional_appointment_path(@professional) %> |
<% end %>
<%= link_to 'Back', professional_appointments_path %>